

DROP FUNCTION "HORG-FR_HISTORY"."add_agentId"("HORG-FR_HISTORY" ."AGENTID");
DROP FUNCTION "HORG-FR_HISTORY"."add_agentLabel"("HORG-FR_HISTORY" ."AGENTLABEL");
DROP FUNCTION "HORG-FR_HISTORY".add_hospital_identification("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_unitIdentification"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY".add_hospital("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_healthcareDivision"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_serviceDepartement"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_serviceDepartement-division"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_managementUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_medicalSpeciality"("HORG-FR_HISTORY" ."MEDICALSPECODE", "HORG-FR_HISTORY" .string);
DROP FUNCTION "HORG-FR_HISTORY"."add_functionalUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_functionalUnit-speciality"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."MEDICALSPECODE", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_functionalUnit-service"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_functionalUnit-managementUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_medicoAdministrativeUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_administrativeUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_administrativeUnit-discipline"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."DISCIPLINECODE", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_administrativeUnit-service"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_administrativeUnit-medicoAdministrativeUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_hospitalizationUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTLABEL", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_medicalDiscipline"("HORG-FR_HISTORY" ."DISCIPLINECODE", "HORG-FR_HISTORY" .string);
DROP FUNCTION "HORG-FR_HISTORY"."add_hospitalizationUnit-service"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."PERIOD");
DROP FUNCTION "HORG-FR_HISTORY"."add_hospitalizationUnit-administrativeUnit"("HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."AGENTID", "HORG-FR_HISTORY" ."PERIOD");
