/*
-- =========================================================================== A
Schema : HORG-FR_HISTORY
Creation Date : 20190417-1527
Encoding : UTF-8, sans BOM, fin de ligne Unix (LF)
Plateforme : PostgreSQL 9.6
Responsable : OntoRelA
Version : v0
Status : dev
Objet :
  delete tables
-- =========================================================================== A
*/

DELETE FROM "HORG-FR_HISTORY"."H0034" ;

DELETE FROM "HORG-FR_HISTORY"."H0035" ;

DELETE FROM "HORG-FR_HISTORY"."H0036" ;

DELETE FROM "HORG-FR_HISTORY"."H0037" ;

DELETE FROM "HORG-FR_HISTORY"."H0038" ;

DELETE FROM "HORG-FR_HISTORY"."H0039" ;

DELETE FROM "HORG-FR_HISTORY"."H003a" ;

DELETE FROM "HORG-FR_HISTORY"."H003b" ;

DELETE FROM "HORG-FR_HISTORY"."H003c" ;

DELETE FROM "HORG-FR_HISTORY"."H003d" ;

DELETE FROM "HORG-FR_HISTORY"."H003e" ;

DELETE FROM "HORG-FR_HISTORY"."H003f" ;

DELETE FROM "HORG-FR_HISTORY"."H0040" ;

DELETE FROM "HORG-FR_HISTORY"."H0041" ;

DELETE FROM "HORG-FR_HISTORY"."H0042" ;

DELETE FROM "HORG-FR_HISTORY"."H0043" ;

DELETE FROM "HORG-FR_HISTORY"."H0044" ;

DELETE FROM "HORG-FR_HISTORY"."H0045" ;

DELETE FROM "HORG-FR_HISTORY"."H0046" ;

DELETE FROM "HORG-FR_HISTORY"."H0047" ;

DELETE FROM "HORG-FR_HISTORY"."H0048" ;

DELETE FROM "HORG-FR_HISTORY"."H0049" ;

DELETE FROM "HORG-FR_HISTORY"."H004a" ;

DELETE FROM "HORG-FR_HISTORY"."H004b" ;

DELETE FROM "HORG-FR_HISTORY"."H004c" ;

DELETE FROM "HORG-FR_HISTORY"."H004d" ;

DELETE FROM "HORG-FR_HISTORY"."H004e" ;

DELETE FROM "HORG-FR_HISTORY"."H004f" ;

DELETE FROM "HORG-FR_HISTORY"."H0050" ;

DELETE FROM "HORG-FR_HISTORY"."H0051" ;

DELETE FROM "HORG-FR_HISTORY"."H0052" ;

DELETE FROM "HORG-FR_HISTORY"."H0053" ;

DELETE FROM "HORG-FR_HISTORY"."H0054" ;

DELETE FROM "HORG-FR_HISTORY"."H0055" ;

DELETE FROM "HORG-FR_HISTORY"."H0056" ;

DELETE FROM "HORG-FR_HISTORY"."H0057" ;

DELETE FROM "HORG-FR_HISTORY"."H0058" ;

DELETE FROM "HORG-FR_HISTORY"."H0059" ;

DELETE FROM "HORG-FR_HISTORY"."H005a" ;

DELETE FROM "HORG-FR_HISTORY"."H005b" ;

DELETE FROM "HORG-FR_HISTORY"."H005c" ;

DELETE FROM "HORG-FR_HISTORY"."H005d" ;

DELETE FROM "HORG-FR_HISTORY"."H005e" ;

DELETE FROM "HORG-FR_HISTORY"."H005f" ;

DELETE FROM "HORG-FR_HISTORY"."H0060" ;

DELETE FROM "HORG-FR_HISTORY"."H0061" ;

DELETE FROM "HORG-FR_HISTORY"."H0062" ;

DELETE FROM "HORG-FR_HISTORY"."H0063" ;

DELETE FROM "HORG-FR_HISTORY"."H0064" ;

DELETE FROM "HORG-FR_HISTORY"."H0065" ;

DELETE FROM "HORG-FR_HISTORY"."H0066" ;

DELETE FROM "HORG-FR_HISTORY"."H0067" ;

DELETE FROM "HORG-FR_HISTORY"."H0068" ;

DELETE FROM "HORG-FR_HISTORY"."H0069" ;

DELETE FROM "HORG-FR_HISTORY"."H006a" ;

DELETE FROM "HORG-FR_HISTORY"."H006b" ;

DELETE FROM "HORG-FR_HISTORY"."H006c" ;

DELETE FROM "HORG-FR_HISTORY"."H006d" ;

DELETE FROM "HORG-FR_HISTORY"."H006e" ;

DELETE FROM "HORG-FR_HISTORY"."H006f" ;

DELETE FROM "HORG-FR_HISTORY"."H0070" ;

DELETE FROM "HORG-FR_HISTORY"."H0071" ;

DELETE FROM "HORG-FR_HISTORY"."H0072" ;

DELETE FROM "HORG-FR_HISTORY"."H0073" ;

DELETE FROM "HORG-FR_HISTORY"."H0074" ;

DELETE FROM "HORG-FR_HISTORY"."H0075" ;

DELETE FROM "HORG-FR_HISTORY"."H0076" ;

DELETE FROM "HORG-FR_HISTORY"."H0077" ;

DELETE FROM "HORG-FR_HISTORY"."H0078" ;

DELETE FROM "HORG-FR_HISTORY"."H0079" ;

DELETE FROM "HORG-FR_HISTORY"."H007a" ;

DELETE FROM "HORG-FR_HISTORY"."H007b" ;

DELETE FROM "HORG-FR_HISTORY"."H007c" ;

DELETE FROM "HORG-FR_HISTORY"."H007d" ;

DELETE FROM "HORG-FR_HISTORY"."H007e" ;

DELETE FROM "HORG-FR_HISTORY"."H007f" ;

DELETE FROM "HORG-FR_HISTORY"."H0080" ;

DELETE FROM "HORG-FR_HISTORY"."H0081" ;

DELETE FROM "HORG-FR_HISTORY"."H0082" ;

DELETE FROM "HORG-FR_HISTORY"."H0083" ;

DELETE FROM "HORG-FR_HISTORY"."H0084" ;

DELETE FROM "HORG-FR_HISTORY"."H0085" ;

DELETE FROM "HORG-FR_HISTORY"."H0086" ;

DELETE FROM "HORG-FR_HISTORY"."H0087" ;

DELETE FROM "HORG-FR_HISTORY"."H0088" ;

DELETE FROM "HORG-FR_HISTORY"."H0089" ;

DELETE FROM "HORG-FR_HISTORY"."H008a" ;

DELETE FROM "HORG-FR_HISTORY"."H008b" ;

DELETE FROM "HORG-FR_HISTORY"."H008c" ;

DELETE FROM "HORG-FR_HISTORY"."H008d" ;

DELETE FROM "HORG-FR_HISTORY"."H008e" ;

DELETE FROM "HORG-FR_HISTORY"."H008f" ;

DELETE FROM "HORG-FR_HISTORY"."H0090" ;

DELETE FROM "HORG-FR_HISTORY"."H0091" ;

DELETE FROM "HORG-FR_HISTORY"."H0092" ;

DELETE FROM "HORG-FR_HISTORY"."H0093" ;

DELETE FROM "HORG-FR_HISTORY"."H0094" ;

DELETE FROM "HORG-FR_HISTORY"."H0095" ;

DELETE FROM "HORG-FR_HISTORY"."H0096" ;

DELETE FROM "HORG-FR_HISTORY"."H0097" ;

DELETE FROM "HORG-FR_HISTORY"."H0098" ;

DELETE FROM "HORG-FR_HISTORY"."H0099" ;

DELETE FROM "HORG-FR_HISTORY"."H009a" ;

DELETE FROM "HORG-FR_HISTORY"."H009b" ;

DELETE FROM "HORG-FR_HISTORY"."H009c" ;

DELETE FROM "HORG-FR_HISTORY"."H009d" ;

DELETE FROM "HORG-FR_HISTORY"."H009e" ;

DELETE FROM "HORG-FR_HISTORY"."H009f" ;

DELETE FROM "HORG-FR_HISTORY"."H00a0" ;

DELETE FROM "HORG-FR_HISTORY"."H00a1" ;

DELETE FROM "HORG-FR_HISTORY"."H00a2" ;

DELETE FROM "HORG-FR_HISTORY"."H00a3" ;

DELETE FROM "HORG-FR_HISTORY"."H00a4" ;

DELETE FROM "HORG-FR_HISTORY"."H00a5" ;

DELETE FROM "HORG-FR_HISTORY"."H00a6" ;

DELETE FROM "HORG-FR_HISTORY"."H00a7" ;

DELETE FROM "HORG-FR_HISTORY"."H00a8" ;

DELETE FROM "HORG-FR_HISTORY"."H00a9" ;

DELETE FROM "HORG-FR_HISTORY"."H00aa" ;

DELETE FROM "HORG-FR_HISTORY"."H00ab" ;

DELETE FROM "HORG-FR_HISTORY"."H00ac" ;

DELETE FROM "HORG-FR_HISTORY"."H00ad" ;

DELETE FROM "HORG-FR_HISTORY"."H00ae" ;

DELETE FROM "HORG-FR_HISTORY"."H00af" ;

DELETE FROM "HORG-FR_HISTORY"."H00b0" ;

DELETE FROM "HORG-FR_HISTORY"."H00b1" ;

DELETE FROM "HORG-FR_HISTORY"."H00b2" ;

DELETE FROM "HORG-FR_HISTORY"."H00b3" ;

DELETE FROM "HORG-FR_HISTORY"."H00b4" ;

DELETE FROM "HORG-FR_HISTORY"."H00b5" ;

DELETE FROM "HORG-FR_HISTORY"."H00b6" ;

DELETE FROM "HORG-FR_HISTORY"."H00b7" ;

DELETE FROM "HORG-FR_HISTORY"."H00b8" ;

DELETE FROM "HORG-FR_HISTORY"."H00b9" ;

DELETE FROM "HORG-FR_HISTORY"."H00ba" ;

DELETE FROM "HORG-FR_HISTORY"."T0013" ;

DELETE FROM "HORG-FR_HISTORY"."T0015" ;

DELETE FROM "HORG-FR_HISTORY"."T0017" ;

DELETE FROM "HORG-FR_HISTORY"."T0011" ;

DELETE FROM "HORG-FR_HISTORY"."T001a" ;

DELETE FROM "HORG-FR_HISTORY"."T001c" ;

