/*
-- =========================================================================== A
Schema : HORG-FR_HISTORY
Creation Date : 20190417-1527
Encoding : UTF-8, sans BOM, fin de ligne Unix (LF)
Plateforme : PostgreSQL 9.6
Responsable : OntoRelA
Version : v0
Status : dev
Objet :
  drop tables
-- =========================================================================== A
*/

DROP TABLE "HORG-FR_HISTORY"."T0017" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."T0011" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."T001a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."T001c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."T0013" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."T0015" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0034" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0035" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0036" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0037" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0038" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0039" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H003a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H003b" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H003c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H003d" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H003e" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H003f" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0040" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0041" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0042" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0043" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0044" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0045" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0046" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0047" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0048" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0049" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H004a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H004b" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H004c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H004d" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H004e" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H004f" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0050" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0051" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0052" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0053" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0054" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0055" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0056" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0057" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0058" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0059" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H005a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H005b" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H005c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H005d" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H005e" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H005f" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0060" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0061" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0062" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0063" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0064" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0065" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0066" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0067" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0068" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0069" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H006a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H006b" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H006c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H006d" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H006e" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H006f" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0070" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0071" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0072" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0073" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0074" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0075" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0076" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0077" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0078" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0079" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H007a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H007b" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H007c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H007d" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H007e" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H007f" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0080" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0081" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0082" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0083" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0084" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0085" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0086" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0087" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0088" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0089" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H008a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H008b" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H008c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H008d" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H008e" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H008f" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0090" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0091" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0092" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0093" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0094" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0095" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0096" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0097" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0098" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H0099" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H009a" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H009b" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H009c" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H009d" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H009e" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H009f" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a0" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a1" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a2" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a3" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a4" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a5" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a6" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a7" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a8" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00a9" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00aa" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00ab" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00ac" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00ad" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00ae" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00af" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b0" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b1" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b2" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b3" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b4" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b5" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b6" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b7" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b8" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00b9" CASCADE;

DROP TABLE "HORG-FR_HISTORY"."H00ba" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."POINT" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."PERIOD" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."dbid_domain" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."value_domain" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."ACTIVITYTYPECODE" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."MEDICALSPECODE" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."PMSI" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."DISCIPLINECODE" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."langString" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."string" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."AGENTLABEL" CASCADE;

DROP DOMAIN "HORG-FR_HISTORY"."AGENTID" CASCADE;

